# Generated by Django 4.1.3 on 2022-11-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='level_choices',
            new_name='level',
        ),
    ]
