# Generated by Django 4.1.3 on 2022-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompany',
            name='city',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
