# Generated by Django 4.1.3 on 2022-11-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1024)),
                ('training_title', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
            ],
        ),
    ]
