# Generated by Django 4.1.3 on 2022-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CooperativeTrainingApp', '0002_alter_company_name_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='training',
            field=models.BooleanField(null=True),
        ),
    ]
