# Generated by Django 4.1.3 on 2022-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CooperativeTrainingApp', '0003_company_information_company_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
